import React from "react";
import TextField from "@mui/material/TextField";
import Autocomplete from "@mui/material/Autocomplete";

export default function Grouped({ onChange }) {
  const options = top100Films.map((option) => {
    const firstLetter = option.title[0].toUpperCase();
    return {
      firstLetter: /[0-9]/.test(firstLetter) ? "0-9" : firstLetter,
      ...option,
    };
  });

  return (
    <Autocomplete
      id="grouped-demo"
      options={options.sort(
        (a, b) => -b.firstLetter.localeCompare(a.firstLetter)
      )}
      groupBy={(option) => option.firstLetter}
      getOptionLabel={(option) => option.title}
      sx={{ width: 300 }}
      onChange={(event, value) => onChange(value)}
      renderInput={(params) => <TextField {...params} label="授業名を選択" />}
    />
  );
}
const top100Films = [
  { title: "英語コミュニケーションⅠ", year: 2023 },
  { title: "英語コミュニケーションⅡ", year: 2023 },
  { title: "英語コミュニケーションⅢ", year: 2023 },
  { title: "英語コミュニケーションⅣ", year: 2023 },
  { title: "プラクティカル・イングリッシュⅠ", year: 2023 },
  { title: "プラクティカル・イングリッシュⅡ", year: 2023 },
  { title: "ドイツ語Ⅰ", year: 2023 },
  { title: "ドイツ語Ⅱ", year: 2023 },
  { title: "ドイツ語Ⅲ", year: 2023 },
  { title: "ドイツ語Ⅳ", year: 2023 },
  { title: "フランス語Ⅰ", year: 2023 },
  { title: "フランス語Ⅱ", year: 2023 },
  { title: "フランス語Ⅲ", year: 2023 },
  { title: "フランス語Ⅳ", year: 2023 },
  { title: "中国語Ⅰ", year: 2023 },
  { title: "中国語Ⅱ", year: 2023 },
  { title: "中国語Ⅲ", year: 2023 },
  { title: "中国語Ⅳ", year: 2023 },
  { title: "体育科学Ⅰ", year: 2023 },
  { title: "体育科学Ⅱ", year: 2023 },
  { title: "体育科学Ⅲ", year: 2023 },
  { title: "体育科学Ⅳ", year: 2023 },
  { title: "人文科学基礎Ⅰ", year: 2023 },
  { title: "人文科学基礎Ⅱ", year: 2023 },
  { title: "人文科学基礎Ⅲ", year: 2023 },
  { title: "人文科学基礎Ⅳ", year: 2023 },
  { title: "アジア文化論Ⅰ", year: 2023 },
  { title: "アジア文化論Ⅱ", year: 2023 },
  { title: "欧米文化論Ⅰ", year: 2023 },
  { title: "欧米文化論Ⅱ", year: 2023 },
  { title: "国際関係論", year: 2023 },
  { title: "文学", year: 2023 },
  { title: "日本国憲法", year: 2023 },
  { title: "心理学", year: 2023 },
  { title: "基礎ゼミナールⅠ", year: 2023 },
  { title: "基礎ゼミナールⅡ", year: 2023 },
  { title: "職業指導論", year: 2023 },
  { title: "日本語Ⅰ", year: 2023 },
  { title: "日本語Ⅱ", year: 2023 },
  { title: "日本語Ⅲ", year: 2023 },
  { title: "日本語Ⅳ", year: 2023 },
  { title: "日本語Ⅴ", year: 2023 },
  { title: "微分積分Ⅰ", year: 2023 },
  { title: "微分積分Ⅱ", year: 2023 },
  { title: "線形代数Ⅰ", year: 2023 },
  { title: "線形代数Ⅱ", year: 2023 },
  { title: "物理学Ⅰ", year: 2023 },
  { title: "物理学Ⅱ", year: 2023 },
  { title: "物理学演習", year: 2023 },
  { title: "物理学実験Ⅰ", year: 2023 },
  { title: "物理学実験Ⅱ", year: 2023 },
  { title: "化学Ⅰ", year: 2023 },
  { title: "化学Ⅱ", year: 2023 },
  { title: "化学実験Ⅰ", year: 2023 },
  { title: "化学実験Ⅱ", year: 2023 },
  { title: "地学Ⅰ", year: 2023 },
  { title: "地学Ⅱ", year: 2023 },
  { title: "地学実験Ⅰ", year: 2023 },
  { title: "地学実験Ⅱ", year: 2023 },
  { title: "生物学", year: 2023 },
  { title: "生物学実験", year: 2023 },
  { title: "理工学概論", year: 2023 },
  { title: "技術者倫理", year: 2023 },
  { title: "コンピューターリテラシー", year: 2023 },
  { title: "情報工学の世界", year: 2023 },
  { title: "情報工学基礎演習", year: 2023 },
  { title: "テクニカルリテラシー", year: 2023 },
  { title: "プラクティカルICT", year: 2023 },
  { title: "情報通信ネットワーク", year: 2023 },
  { title: "情報理論", year: 2023 },
  { title: "情報セキュリティ", year: 2023 },
  { title: "情報通信システム", year: 2023 },
  { title: "信号伝送論", year: 2023 },
  { title: "符号理論", year: 2023 },
  { title: "ワイヤレス通信", year: 2023 },
  { title: "コンピュータアーキテクチャⅠ", year: 2023 },
  { title: "コンピュータアーキテクチャⅡ", year: 2023 },
  { title: "ディジタル回路Ⅰ", year: 2023 },
  { title: "ディジタル回路Ⅱ", year: 2023 },
  { title: "電気電子回路Ⅰ", year: 2023 },
  { title: "電気電子回路Ⅱ", year: 2023 },
  { title: "ディジタル信号処理Ⅰ", year: 2023 },
  { title: "ディジタル信号処理Ⅱ", year: 2023 },
  { title: "システム制御", year: 2023 },
  { title: "フィジカルコンピューティング", year: 2023 },
  { title: "ハードウェア記述言語", year: 2023 },
  { title: "センサ工学", year: 2023 },
  { title: "集積回路設計", year: 2023 },
  { title: "アルゴリズム・データ構造", year: 2023 },
  { title: "オペレーティングシステム", year: 2023 },
  { title: "データベース", year: 2023 },
  { title: "ソフトウェア工学", year: 2023 },
  { title: "言語・オートマトン", year: 2023 },
  { title: "人工知能", year: 2023 },
  { title: "数値解析", year: 2023 },
  { title: "コンパイラ", year: 2023 },
  { title: "プログラミング言語論", year: 2023 },
  { title: "パターン認識", year: 2023 },
  { title: "応用アルゴリズム", year: 2023 },
  { title: "数理計画法", year: 2023 },
  { title: "マルチメディア基礎", year: 2023 },
  { title: "画像処理", year: 2023 },
  { title: "コンピュータグラフィックス", year: 2023 },
  { title: "コンピュータビジョン", year: 2023 },
  { title: "感性情報処理", year: 2023 },
  { title: "音声・音響信号処理", year: 2023 },
  { title: "バーチャルリアリティ", year: 2023 },
  { title: "言語情報処理", year: 2023 },
  { title: "離散数学", year: 2023 },
  { title: "確率・統計", year: 2023 },
  { title: "データサイエンス基礎", year: 2023 },
  { title: "応用解析", year: 2023 },
  { title: "電磁気学", year: 2023 },
  { title: "プログラミング演習Ⅰ", year: 2023 },
  { title: "プログラミング演習Ⅱ", year: 2023 },
  { title: "プログラミング演習Ⅲ", year: 2023 },
  { title: "プログラミング演習Ⅳ", year: 2023 },
  { title: "情報工学実験Ⅰ", year: 2023 },
  { title: "情報工学実験Ⅱ", year: 2023 },
  { title: "インターンシップ", year: 2023 },
  { title: "グローバルゼミナール", year: 2023 },
  { title: "キャリアゼミナール", year: 2023 },
  { title: "研究ゼミナール", year: 2023 },
  { title: "創造的思考法", year: 2023 },
  { title: "研究開発リテラシー", year: 2023 },
  { title: "アプリケーション開発", year: 2023 },
  { title: "PBL概論", year: 2023 },
  { title: "先進プロジェクト実験Ⅰ", year: 2023 },
  { title: "先進プロジェクト実験Ⅱ", year: 2023 },
  { title: "先進プロジェクトゼミナール", year: 2023 },
  { title: "卒業研究", year: 2023 },
];
